spring:
 cloud:
  gateway:
    globalcors:
      corsConfigurations:
        '[/**]':
           allowedOrigins: "*"
           allowedHeaders: "*"
           allowedMethods:
             - GET
             - POST
             - PUT
             - DELETE
      default-filters:
           - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin